=== malux24/bryanCafe/branches.dtd
<!ELEMENT branches (branch+)>
<!ELEMENT branch (name, address, phone, hours, maplink)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT hours (#PCDATA)>
<!ELEMENT maplink (#PCDATA)>

=== malux24/bryanCafe/branches.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE branches SYSTEM "branches.dtd">
<branches>
  <branch>
    <name>Surry Hills Branch</name>
    <address>76 Devonshire St, Surry Hills NSW</address>
    <phone>02 9211 1234</phone>
    <hours>Mon - Fri: 6:00 to 14:30, Sat - Sun: 7:00 to 15:00</hours>
    <maplink>https://maps.google.com/</maplink>
  </branch>

  <branch>
    <name>Haymarket Branch</name>
    <address>451 Pitt St, Haymarket Sydney, NSW</address>
    <phone>02 9262 5678</phone>
    <hours>Mon - Fri: 6:00 to 16:00, Sat - Sun: 7:00 to 15:00</hours>
    <maplink>https://maps.google.com/</maplink>
  </branch>

  <branch>
    <name>Circular Quay Branch</name>
    <address>31 Alfred Street, Circular Quay, NSW</address>
    <phone>02 8971 9101</phone>
    <hours>Mon - Fri: 6:00 to 16:00, Sat - Sun: 7:00 to 15:00</hours>
    <maplink>https://maps.google.com/</maplink>
  </branch>
</branches>
